# Generated by Django 5.2.7 on 2025-10-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Estimator', 'Estimator'), ('Project Manager', 'Project Manager')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Estimator', 'Estimator'), ('Project Manager', 'Project Manager')], default='Admin', max_length=100),
        ),
    ]
