# Generated by Django 5.2.7 on 2025-10-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_invitation_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
