# Generated by Django 5.2.4 on 2025-11-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_invitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
