# Generated by Django 5.2.4 on 2025-10-29 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Material name (e.g., Interior finishing, Wood, Steel)', max_length=255)),
                ('category', models.CharField(help_text='Category (e.g., Metals, Woods, Soft Goods)', max_length=100)),
                ('target_room', models.CharField(help_text='Target room (e.g., Select Room, Bedroom, Kitchen)', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in dollars', max_digits=10)),
                ('unit', models.CharField(default='unit', help_text='Unit of measurement (e.g., unit, sq ft, linear ft)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional description or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this material is available for use')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['category', 'name'],
            },
        ),
    ]
