# Generated by Django 5.2.4 on 2025-11-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(help_text='Name of the component', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the component', null=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price of the component', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentEstimateQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of estimate default needed', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Component Estimate Quantity',
                'verbose_name_plural': 'Component Estimate Quantities',
            },
        ),
        migrations.CreateModel(
            name='ComponentMaterialQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of material needed', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Component Material Quantity',
                'verbose_name_plural': 'Component Material Quantities',
            },
        ),
        migrations.CreateModel(
            name='EstimateDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the estimate default', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the estimate default', null=True)),
                ('category', models.CharField(help_text='Category of the estimate', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estimate Default',
                'verbose_name_plural': 'Estimate Defaults',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(help_text='Name of the material', max_length=255)),
                ('supplier', models.CharField(help_text='Supplier name', max_length=255)),
                ('category', models.CharField(help_text='Material category', max_length=255)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., kg, liter, piece)', max_length=50)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, help_text='Cost per unit', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
