# Generated by Django 5.2.4 on 2025-11-18 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admindashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='componentestimatequantity',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_quantities', to='admindashboard.component'),
        ),
        migrations.AddField(
            model_name='componentmaterialquantity',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_quantities', to='admindashboard.component'),
        ),
        migrations.AddField(
            model_name='estimatedefaults',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_defaults_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='componentestimatequantity',
            name='estimate_default',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_quantities', to='admindashboard.estimatedefaults'),
        ),
        migrations.AddField(
            model_name='component',
            name='estimate_defaults',
            field=models.ManyToManyField(blank=True, help_text='Estimate defaults associated with this component', related_name='components', through='admindashboard.ComponentEstimateQuantity', to='admindashboard.estimatedefaults'),
        ),
        migrations.AddField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='componentmaterialquantity',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_quantities', to='admindashboard.material'),
        ),
        migrations.AddField(
            model_name='component',
            name='material_used',
            field=models.ManyToManyField(blank=True, help_text='Materials used in this component', related_name='components', through='admindashboard.ComponentMaterialQuantity', to='admindashboard.material'),
        ),
        migrations.AlterUniqueTogether(
            name='componentestimatequantity',
            unique_together={('component', 'estimate_default')},
        ),
        migrations.AlterUniqueTogether(
            name='componentmaterialquantity',
            unique_together={('component', 'material')},
        ),
    ]
