# Generated by Django 5.2.7 on 2025-10-29 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Component name (e.g., Wall, Roof, Floor)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional description or notes', null=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in dollars', max_digits=10)),
                ('Labor_hours', models.DecimalField(decimal_places=2, help_text='Estimated labor hours required', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this component is available for use')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components_created', to=settings.AUTH_USER_MODEL)),
                ('metarials', models.ManyToManyField(help_text='Materials associated with this component', related_name='components', to='admindashboard.material')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'ordering': ['name'],
            },
        ),
    ]
