# Generated by Django 5.2.4 on 2025-10-29 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_component'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate_defult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Estimate template name (e.g., Standard Residential, Commercial Basic)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional description or notes', null=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Default cost in dollars', max_digits=10)),
                ('cretegory', models.CharField(help_text='Category (e.g., Residential, Commercial)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this estimate template is active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_templates_created', to=settings.AUTH_USER_MODEL)),
                ('metarials', models.ManyToManyField(help_text='Materials included in this estimate template', related_name='estimate_templates', to='admindashboard.material')),
            ],
            options={
                'verbose_name': 'Estimate Template',
                'verbose_name_plural': 'Estimate Templates',
                'ordering': ['name'],
            },
        ),
    ]
