# Generated by Django 5.2.4 on 2025-11-03 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0003_estimate_defult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate_defult',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='estimate_defult',
            name='metarials',
        ),
        migrations.RemoveField(
            model_name='material',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Estimate_defult',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
