# Generated by Django 5.2.4 on 2025-11-03 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admindashboard', '0004_remove_estimate_defult_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(help_text='Name of the material', max_length=255)),
                ('supplier', models.CharField(help_text='Supplier name', max_length=255)),
                ('category', models.CharField(help_text='Material category', max_length=255)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., kg, liter, piece)', max_length=50)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, help_text='Cost per unit', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
