# Generated by Django 5.2.4 on 2025-11-03 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the estimate default', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the estimate default', null=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Total cost', max_digits=10)),
                ('category', models.CharField(help_text='Category of the estimate', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_defaults_created', to=settings.AUTH_USER_MODEL)),
                ('current_materials', models.ManyToManyField(blank=True, help_text='Materials associated with this estimate default', related_name='estimate_defaults', to='admindashboard.material')),
            ],
            options={
                'verbose_name': 'Estimate Default',
                'verbose_name_plural': 'Estimate Defaults',
                'ordering': ['-created_at'],
            },
        ),
    ]
