# Generated by Django 5.2.4 on 2025-11-03 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0006_estimatedefaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(help_text='Name of the component', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the component', null=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price of the component', max_digits=10)),
                ('labor_hours', models.DecimalField(decimal_places=2, help_text='Labor hours required', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components_created', to=settings.AUTH_USER_MODEL)),
                ('material_used', models.ManyToManyField(blank=True, help_text='Materials used in this component', related_name='components', to='admindashboard.material')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'ordering': ['-created_at'],
            },
        ),
    ]
