# Generated by Django 5.2.4 on 2025-11-19 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project_manager', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(help_text='Date of work (automatically set)')),
                ('start_time', models.DateTimeField(help_text='When employee started work on this task')),
                ('end_time', models.DateTimeField(blank=True, help_text='When employee stopped work on this task', null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Total time worked in seconds')),
                ('is_active', models.BooleanField(default=True, help_text='True if timer is currently running')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_timers', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='Project_manager.task')),
            ],
            options={
                'verbose_name': 'Task Timer',
                'verbose_name_plural': 'Task Timers',
                'ordering': ['-work_date', '-start_time'],
                'indexes': [models.Index(fields=['employee', 'work_date'], name='emopye_task_employe_0fdb19_idx'), models.Index(fields=['task', 'work_date'], name='emopye_task_task_id_168749_idx'), models.Index(fields=['is_active'], name='emopye_task_is_acti_db66c1_idx')],
            },
        ),
    ]
