# Generated by Django 5.2.4 on 2025-11-18 02:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('estimate_number', models.CharField(blank=True, help_text='Estimate number for tracking', max_length=100, null=True, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('estimate_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, help_text='End/completion date of the project', null=True)),
                ('targeted_rooms', models.JSONField(blank=True, default=list, help_text='Array of targeted rooms for the estimate')),
                ('targeted_rooms_updated', models.DateTimeField(blank=True, help_text='Timestamp when targeted_rooms was last updated', null=True)),
                ('image_1', models.URLField(blank=True, help_text='First reference image URL', null=True)),
                ('image_2', models.URLField(blank=True, help_text='Second reference image URL', null=True)),
                ('profit_margin', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('income_tax', models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.JSONField(default=list, help_text='Array of items: [{item_type, item_id, quantity, unit_price}]')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='estimator_e_status_86fcdb_idx'), models.Index(fields=['-created_at'], name='estimator_e_created_24d6d8_idx')],
            },
        ),
    ]
