# Generated by Django 5.2.7 on 2025-10-16 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
